// <auto-generated />
using System;
using CodenameApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAppSandbox.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419114957_FixClueFK")]
    partial class FixClueFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CodenameApp.Domain.Clue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("Clues");
                });

            modelBuilder.Entity("CodenameApp.Domain.Codename", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Codenames");
                });

            modelBuilder.Entity("CodenameApp.Domain.GameCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRoomId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("GameCards");
                });

            modelBuilder.Entity("CodenameApp.Domain.GameRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("CodenameApp.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CodenameApp.Domain.Clue", b =>
                {
                    b.HasOne("CodenameApp.Domain.GameRoom", null)
                        .WithMany("Clues")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodenameApp.Domain.GameCard", b =>
                {
                    b.HasOne("CodenameApp.Domain.GameRoom", null)
                        .WithMany("Cards")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodenameApp.Domain.GameRoom", b =>
                {
                    b.OwnsOne("CodenameApp.Domain.GameState", "State", b1 =>
                        {
                            b1.Property<Guid>("GameRoomId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsStarted")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Phase")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Round")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Winner")
                                .HasColumnType("TEXT");

                            b1.HasKey("GameRoomId");

                            b1.ToTable("GameRooms");

                            b1.WithOwner()
                                .HasForeignKey("GameRoomId");
                        });

                    b.Navigation("State")
                        .IsRequired();
                });

            modelBuilder.Entity("CodenameApp.Domain.Player", b =>
                {
                    b.HasOne("CodenameApp.Domain.GameRoom", "GameRoom")
                        .WithMany("Players")
                        .HasForeignKey("GameRoomId");

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("CodenameApp.Domain.GameRoom", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Clues");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
